source 'https://rubygems.org'

gem 'rails', '4.0.0.rc2'

group :development, :test do
  gem 'mysql2', '0.3.11'
  gem 'rspec-rails', '2.11.0'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '4.0.0.rc2'

  gem 'coffee-rails', '4.0.0'

  gem 'uglifier', '1.3.0'
end

gem 'jquery-rails', '3.0.4'

group :test do
  gem 'capybara', '1.1.2'
end
